### ISSUE TITLE
Server crashing on 1.19.2 caused by completeconfig - NoSuchFieldError: checkbox

### ISSUE THREAD

**Issue by noname9312** [Palyon-dev/CustomPortals#26]
I have removed all mods (and config folder) except of the fabric api and the custom portals mod. Tested it with and without the completeconfig mod.

The relevant part seems to be:
`Caused by: java.lang.NoSuchFieldError: checkbox
at me.lortseam.completeconfig.data.BooleanEntry.<init>(BooleanEntry.java:26) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]`

Here is the complete crash output:
`[01:29:41] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'customportals'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.6.jar:?]
Caused by: java.lang.NoSuchFieldError: checkbox
        at me.lortseam.completeconfig.data.BooleanEntry.<init>(BooleanEntry.java:26) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Entry.create(Entry.java:42) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.EntrySet.lambda$resolve$1(EntrySet.java:31) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.lortseam.completeconfig.data.EntrySet.resolve(EntrySet.java:32) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:58) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.ClusterSet.resolve(ClusterSet.java:13) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:108) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Parent.lambda$resolveContainer$6(Parent.java:97) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:97) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:110) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Config.lambda$new$0(Config.java:51) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Config.deserialize(Config.java:94) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at me.lortseam.completeconfig.data.Config.load(Config.java:121) ~[completeconfig-base-2.1.0-ac48f735a60effdb.jar:?]
        at dev.custom.portals.CustomPortals.onInitialize(CustomPortals.java:36) ~[custom-portals-3.2.0-1.19.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
        ... 6 more`

Edit:
Okay so I found out it works with the loader fabric-loader-0.14.25
but im using the loader with fabric-loader-0.15.6. the server has already +200 mods. Downgrading the loader creates a lot of incompatibilities.
Could you please fix it for 0.15.6?

**Comment by Palyon-dev** [comment]
[Known CompleteConfig issue](https://github.com/Lortseam/completeconfig/issues/22l). Was fixed in v2.5.2 of CompleteConfig, but this is for 1.20. They would need to fix it on their end for 1.19 as well. Otherwise I'm afraid the only option is to downgrade the loader.

**Comment by noname9312** [comment]
I see CompleteConfig is depreacted. Would using YetAnotherConfigLib be an option?

**Comment by Palyon-dev** [comment]
It's deprecated because it's not being updated to 1.21, so I do need to switch to YACL anyway at some point. I'll reopen this to remind myself to do that

**Comment by praecipitator** [comment]
Happens on 1.20.1 as well, only on the server side, however. No viable version of CompleteConfig has been found.

**Comment by rgamer82** [comment]
@Palyon-dev So what I'm getting from the 1.20.1 comment is that I use the 1.20.4 version of the mod in my 1.20.1 server. Even when I use that, it requests Minecraft version 1.20.4 and not 1.20.1 so not sure what you mean by the fix.

**Comment by rgamer82** [comment]
Disregard that last comment. I am a complete idiot. What you do is install CompleteConfig 2.5.2 and then install version 3.3.1 for 1.20.1

**Comment by Palyon-dev** [comment]
CompleteConfig has been replaced with YACL for versions for Minecraft 1.20.1 and up. Unfortunately switching to YACL for the 1.19.2 release would be a major undertaking as the 1.19.2 version of YACL does not have many of its modern features that my mod now relies on. I'll once again have to leave it up to the developer of CompleteConfig to port their fix for this issue to 1.19.2 if they choose.
